[package]
name = "user-command"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
axum = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
async-nats = { workspace = true }
async-graphql = { workspace = true }
async-graphql-axum = { workspace = true }
base = { workspace = true }
chrono = { workspace = true }
educe = { workspace = true }
enum_dispatch = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
user-common = { path = "../common" }
validator = { workspace = true }
thiserror = { workspace = true }
struct-field-names-as-array = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, features = [
    "runtime-tokio-rustls",
    "sqlite",
    "chrono",
    "postgres",
] }
tokio = { workspace = true, features = ["full"] }
ulid = { workspace = true }
once_cell = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
axum-test = { workspace = true }
