[workspace]
resolver = "2"

members = ["util"]

[workspace.package]
version = "0.0.1"
edition = "2021"
description = "Stitchmate Monorepo"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
anyhow = "1.0.80"
async-trait = "0.1.83"
