[package]
name = "base"
description = "a framework for eventing driven applications in CQRS style, organized hexgonally."
license = "MIT"
version = "0.2.0"
edition = "2021"

[features]
derive = ["base-derive"]

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.68"
async-nats = "0.33.0"
deadpool-redis = "0.12.0"
valuable = { workspace = true, features = ["derive"] }
notify = "5.1.0"
secrecy = { workspace = true, features = ["alloc", "serde"] }
base-derive = { path = "../base-derive", optional = true }
chrono = { version = "0.4.23", features = ["serde"] }
educe = "0.4.22"
futures = "0.3.30"
futures-util = "0.3.30"
once_cell = "1.13.0"
redis_cluster_async = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
sqlx = { version = "0.7", features = [
    "runtime-tokio-rustls",
    "sqlite",
    "chrono",
    "postgres",
] }
tracing = "0.1.37"
tokio = { version = "1.22.0", features = ["full"] }
tokio-stream = "0.1.11"
ulid = "1.0.0"
thiserror = "1.0.40"

[package.metadata.docs.rs]
all-features = true
