[package]
name = "base-derive"
description = "macros for base"
license = "MIT"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["extra-traits"] }

[dev-dependencies]
base = { path = "../base" }
trybuild = "1"