[workspace]
resolver = "2"

members = ["base", "base-derive"]

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.66"
async-trait = "0.1.73"
async-nats = "0.33.0"
deadpool-redis = "0.12.0"
notify = "5.1.0"
chrono = { version = "0.4.23", features = ["serde"] }
educe = "0.4.22"
futures = "0.3.30"
futures-util = "0.3.30"
nats = "0.24.0"
once_cell = "1.13.0"
redis_cluster_async = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
valuable = { version = "0.1.0", features = ["derive"] }
secrecy = { version = "0.8.0", features = ["alloc", "serde"] }
sqlx = { version = "0.7", features = [
  "runtime-tokio-rustls",
  "sqlite",
  "chrono",
  "postgres",
] }
tracing = "0.1.37"
tokio = { version = "1.22.0", features = ["full"] }
tokio-stream = "0.1.11"
ulid = "1.0.0"
thiserror = "1.0.48"
